[package]
name = "green_top_verdigris"
version = "0.1.0"
edition = "2021"

[dependencies]
raylib = "3.7.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
